#%RAML 1.0 DataType

type: object
properties: 
  poNumber: string
  signatureRequiredFlag: boolean
  shipInstructions: string
  giftWrapFlag: boolean
  giftWrapMessage: string
  currencyCode: string
  subTotal: number
  email: string